apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-2          
  namespace: argocd-namespace-3
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami         
    chart: nginx
    targetRevision: 18.3.5
    helm:
      releaseName: nginx-3
      values: |
        replicaCount: 2
  destination:         
    name: in-cluster
    namespace: argocd-namespace-3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

